name: sulyap_kapampangan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  objectbox: ^4.0.2
  objectbox_flutter_libs: any
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: 4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/background1.png
    - assets/background2.png
    - assets/background3.png
    - assets/background4.png
    - assets/easy_mode_images/buac.png
    - assets/easy_mode_images/bale.png
    - assets/easy_mode_images/mabayat.png
    - assets/easy_mode_images/kotsi.png
    - assets/easy_mode_images/pitudturan.png
    - assets/logo.png
    - assets/logo_purple.png