// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUDWd4HJYhzB0bh9vRfgX3Yzv1Q2Knwec',
    appId: '1:1055933765922:web:f076d27af83a658a4aad7b',
    messagingSenderId: '1055933765922',
    projectId: 'sulyap-kapampangan',
    authDomain: 'sulyap-kapampangan.firebaseapp.com',
    storageBucket: 'sulyap-kapampangan.appspot.com',
    measurementId: 'G-EB2CEMMK08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbBqga1DqE-vYmPRfdHxMDFJoOghILo64',
    appId: '1:1055933765922:android:906f2f186cc3a56d4aad7b',
    messagingSenderId: '1055933765922',
    projectId: 'sulyap-kapampangan',
    storageBucket: 'sulyap-kapampangan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC_7YChBec615xWuKT0aq5Kshfr3OCpcw',
    appId: '1:1055933765922:ios:6af0c0d9b8080bbc4aad7b',
    messagingSenderId: '1055933765922',
    projectId: 'sulyap-kapampangan',
    storageBucket: 'sulyap-kapampangan.appspot.com',
    iosBundleId: 'com.example.sulyapKapampangan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC_7YChBec615xWuKT0aq5Kshfr3OCpcw',
    appId: '1:1055933765922:ios:6af0c0d9b8080bbc4aad7b',
    messagingSenderId: '1055933765922',
    projectId: 'sulyap-kapampangan',
    storageBucket: 'sulyap-kapampangan.appspot.com',
    iosBundleId: 'com.example.sulyapKapampangan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUDWd4HJYhzB0bh9vRfgX3Yzv1Q2Knwec',
    appId: '1:1055933765922:web:413cf5242d4f64064aad7b',
    messagingSenderId: '1055933765922',
    projectId: 'sulyap-kapampangan',
    authDomain: 'sulyap-kapampangan.firebaseapp.com',
    storageBucket: 'sulyap-kapampangan.appspot.com',
    measurementId: 'G-D7JPJTPDFJ',
  );
}
